### ISSUE TITLE
[FEATURE REQUEST] Produce documentation on how to compile

### ISSUE THREAD

**Issue by CBenghi** [litrl/litrl_code#14]
**Is your feature request related to a problem? Please describe.**
I'm having problems to what I need to do to compile and run the solution from code.

**Describe the solution you'd like**
Have a list of steps needed to have the software working in the debug environment.

**Describe alternatives you've considered**
Reading the available documentation and browsing the sources worked to some extent but then I got a run-time error I don't understand.

**Additional context**
The Visual studio side of things seems to work and dependencies are downloaded via nuget, but the integration with Python is not clear to me. So I cannot go past the following file not found error, perhaps a dependency is missing... I have Python installed on the system.

System.ComponentModel.Win32Exception
  HResult=0x80004005
  Message=The system cannot find the file specified
  Source=System
  StackTrace:
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Decoy.FrmMain.StartClickbaitDetector() in C:\Data\Dev\Other\Joss\litrl_code\vs_solution\LITRL\Decoy\FrmMain.cs:line 507
   at Decoy.FrmMain.FrmMain_Load(Object sender, EventArgs e) in C:\Data\Dev\Other\Joss\litrl_code\vs_solution\LITRL\Decoy\FrmMain.cs:line 174
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by brogly-zz** [comment]
Hi Claudio, I will follow the steps myself on a new clone and correct the documentation - thanks for bringing this up.

**Comment by brogly-zz** [comment]
Hi Claudio, this issue can be fixed by running the "install.cmd" file in the build output folder (.....bin/x64/Debug or Release)... can you try and run this batch script to create the python environment? Then you should be able to start the project in Visual Studio

Also I noticed that these files might get included as unstaged files... I will need to make sure these are ignored

**Comment by brogly-zz** [comment]
I have also updated the docs on the Development & build process page; let me know if this is more clear.

**Comment by CBenghi** [comment]
Thanks @brogly,
your instructions worked.
However I'd suggest to put a link to the wiki pages from the readme.md
What I'd do is to to have something of the sort of  "Compiling and running" similarly to the existing " "Installing the software"  section.

**Comment by brogly-zz** [comment]
@CBenghi I have added this section to the readme, thanks for pointing this out. I will leave the issue open until you take a look.
